/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package si.GUI;

import java.util.logging.Level;
import java.util.logging.Logger;
import si.api.utils.BufferData;
import si.api.utils.BufferDataV2;
import si.api.utils.ComplexInstruction;
import si.dispatcher.DispatcherV2;
import si.planner.PlannerV2;

/**
 *
 * @author Aires
 */
public class guiONE extends javax.swing.JFrame {

    /**
     * Creates new form guiONE
     */
    public guiONE() {
        initComponents();
        this.setResizable(false); 
        //cell2
        jLabel4.setVisible(false);
        jZ2Field.setVisible(false);
        jX2Field.setVisible(false);
        
        //stations
        jLabel2.setVisible(false);
        jLeftStationButton.setVisible(false);
        jRightStationButton.setVisible(false);
        
        //error label
        jLabel7.setVisible(false);
        jLabel9.setVisible(false);
        jLabel10.setVisible(false);
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        action_choose = new javax.swing.ButtonGroup();
        Station_choose = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPutButton = new javax.swing.JRadioButton();
        jGetButton = new javax.swing.JRadioButton();
        jLeftStationButton = new javax.swing.JRadioButton();
        jRightStationButton = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jZ2Field = new javax.swing.JTextField();
        jX2Field = new javax.swing.JTextField();
        jZ1Field = new javax.swing.JTextField();
        jX1Field = new javax.swing.JTextField();
        jSwitchButton = new javax.swing.JRadioButton();
        jGoButton = new javax.swing.JButton();
        jStopButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel1.setText("Action");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel2.setText("Station");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel3.setText("Cell");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, -1, -1));

        jLabel4.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel4.setText("Cell 2");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));

        action_choose.add(jPutButton);
        jPutButton.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jPutButton.setText("Put in Cell");
        jPutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(jPutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        action_choose.add(jGetButton);
        jGetButton.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jGetButton.setText("Get from Cell");
        jGetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGetButtonActionPerformed(evt);
            }
        });
        getContentPane().add(jGetButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        Station_choose.add(jLeftStationButton);
        jLeftStationButton.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLeftStationButton.setText("Left");
        getContentPane().add(jLeftStationButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, -1, -1));

        Station_choose.add(jRightStationButton);
        jRightStationButton.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jRightStationButton.setText("Right");
        getContentPane().add(jRightStationButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel5.setText("X");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 10, -1));

        jLabel6.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel6.setText("Z");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 10, 20));

        jZ2Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jZ2FieldActionPerformed(evt);
            }
        });
        getContentPane().add(jZ2Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 40, -1));
        getContentPane().add(jX2Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 40, -1));

        jZ1Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jZ1FieldActionPerformed(evt);
            }
        });
        getContentPane().add(jZ1Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 40, -1));
        getContentPane().add(jX1Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 40, -1));

        action_choose.add(jSwitchButton);
        jSwitchButton.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jSwitchButton.setText("Switch Cell");
        jSwitchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSwitchButtonActionPerformed(evt);
            }
        });
        getContentPane().add(jSwitchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jGoButton.setFont(new java.awt.Font("Calibri Light", 0, 36)); // NOI18N
        jGoButton.setText("Go");
        jGoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGoButtonActionPerformed(evt);
            }
        });
        getContentPane().add(jGoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 100, 60));

        jStopButton.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jStopButton.setText("STOP");
        getContentPane().add(jStopButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 100, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/si/box.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, -1, -1));

        jLabel7.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 51));
        jLabel7.setText("Invalid inputs");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 80, 20));

        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("X=[1-5]");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, -1, -1));

        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("Z=[1-10]");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPutButtonActionPerformed
        //cell2
        jLabel4.setVisible(false);
        jZ2Field.setVisible(false);
        jX2Field.setVisible(false);
        jZ2Field.setText("");
        jX2Field.setText("");
        
        //stations
        jLabel2.setVisible(true);
        jLeftStationButton.setVisible(true);
        jRightStationButton.setVisible(true);
        
// TODO add your handling code here:
    }//GEN-LAST:event_jPutButtonActionPerformed

    private void jZ2FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jZ2FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jZ2FieldActionPerformed

    private void jZ1FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jZ1FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jZ1FieldActionPerformed

    private void jGoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGoButtonActionPerformed
        // TODO add your handling code here:
        int x, z, x_dest, z_dest;
        jLabel7.setVisible(false);
        jLabel9.setVisible(false);
        jLabel10.setVisible(false);
        try {
            x = Integer.parseInt(jX1Field.getText());
            z = Integer.parseInt(jZ1Field.getText());
            
            if(jPutButton.isSelected()){
                if(jLeftStationButton.isSelected())
                    data.ComplexInstruction.add(new ComplexInstruction(x,z,"PUT_PIECE", 0, 0));
                else if(jRightStationButton.isSelected())
                     data.ComplexInstruction.add(new ComplexInstruction(x,z,"PUT_PIECE", 9, 0));
            }
            if(jGetButton.isSelected()){
                if(jLeftStationButton.isSelected())
                    data.ComplexInstruction.add(new ComplexInstruction(x,z,"GET_PIECE", 0, 0));
                else if(jRightStationButton.isSelected())
                    data.ComplexInstruction.add(new ComplexInstruction(x,z,"GET_PIECE", 9, 0));                    
            }
            if (jSwitchButton.isSelected()) {
                x_dest = Integer.parseInt(jX2Field.getText());
                z_dest = Integer.parseInt(jZ2Field.getText());
                data.ComplexInstruction.add(new ComplexInstruction(x,z,"SWITCH_PIECE", x_dest, z_dest));
            }
            
        } catch (Exception e) {
            jLabel7.setVisible(true);
            jLabel9.setVisible(true);
            jLabel10.setVisible(true);
        }


       
       /*
       if(conditions_to_process()){
           
       }else{
           
       }
       */
       
        
    }//GEN-LAST:event_jGoButtonActionPerformed

    private void jGetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGetButtonActionPerformed
        //cell2
        jLabel4.setVisible(false);
        jZ2Field.setVisible(false);
        jX2Field.setVisible(false);
        jZ2Field.setText("");
        jX2Field.setText("");
        
        
        //stations
        jLabel2.setVisible(true);
        jLeftStationButton.setVisible(true);
        jRightStationButton.setVisible(true);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jGetButtonActionPerformed

    private void jSwitchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSwitchButtonActionPerformed

        //cell2
        jLabel4.setVisible(true);
        jZ2Field.setVisible(true);
        jX2Field.setVisible(true);
        
        //stations
        jLabel2.setVisible(false);
        jLeftStationButton.setVisible(false);
        jRightStationButton.setVisible(false);

// TODO add your handling code here:
    }//GEN-LAST:event_jSwitchButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(guiONE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(guiONE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(guiONE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(guiONE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        data = new BufferDataV2();
        try {
            Thread.sleep(1000);
        } catch (InterruptedException ex) {
            Logger.getLogger(guiONE.class.getName()).log(Level.SEVERE, null, ex);
        }
        new Thread(new DispatcherV2(data)).start();
        new Thread(new PlannerV2(data)).start();
        //new Thread(new Monitor(bd)).start();
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new guiONE().setVisible(true);
                
                
            }
        });
        
        
        
    }
    
    
    private boolean conditions_to_process(){
        
        
        if (
            //cell 1 with put and get from station;
            (((Integer.parseInt(jZ1Field.getText())) <= 5 && (Integer.parseInt(jZ1Field.getText()) >= 1)) && 
            ((Integer.parseInt(jX1Field.getText()) <= 10) && (Integer.parseInt(jX1Field.getText()) >= 1)) &&
            (jPutButton.isSelected() || jGetButton.isSelected()) &&
            (jLeftStationButton.isSelected() || jRightStationButton.isSelected()))
            //cell 1 to cell 2
            || (jSwitchButton.isSelected() && 
            ((Integer.parseInt(jZ1Field.getText())) <= 5 && (Integer.parseInt(jZ1Field.getText()) >= 1)) && 
            ((Integer.parseInt(jX1Field.getText()) <= 10) && (Integer.parseInt(jX1Field.getText()) >= 1)) &&
            ((Integer.parseInt(jZ2Field.getText())) <= 5 && (Integer.parseInt(jZ2Field.getText()) >= 1)) && 
            ((Integer.parseInt(jX2Field.getText()) <= 10) && (Integer.parseInt(jX2Field.getText()) >= 1)))
                 
            //cell 1 with put and get from cell;   
                
            ){
            
            
            
            
        //well done
            jLabel7.setVisible(false);
            jLabel9.setVisible(false);
            jLabel10.setVisible(false);
        }
        else
        {
            //error input
            jLabel7.setVisible(true);
            jLabel9.setVisible(true);
            jLabel10.setVisible(true);
        }
        
        
        
        
        
        
        
        
        return false;
    }
    
    private static BufferData data;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Station_choose;
    private javax.swing.ButtonGroup action_choose;
    private javax.swing.JRadioButton jGetButton;
    private javax.swing.JButton jGoButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jLeftStationButton;
    private javax.swing.JRadioButton jPutButton;
    private javax.swing.JRadioButton jRightStationButton;
    private javax.swing.JButton jStopButton;
    private javax.swing.JRadioButton jSwitchButton;
    private javax.swing.JTextField jX1Field;
    private javax.swing.JTextField jX2Field;
    private javax.swing.JTextField jZ1Field;
    private javax.swing.JTextField jZ2Field;
    // End of variables declaration//GEN-END:variables
}
