// hardware.cpp : Defines the exported functions for the DLL application.
//

#include "stdafx.h"

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdio.h>
#include <interface.h>

#ifndef _Included_trab1_Hardware
#define _Included_trab1_Hardware
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     trab1_Hardware
	* Method:    initialize_kit
	* Signature: ()V
	*/
	JNIEXPORT void JNICALL Java_trab1_Hardware_initialize_1kit
		(JNIEnv *, jobject){
		create_DI_channel(port);
		create_DI_channel(port);
		create_DI_channel(port);
		create_DI_channel(port);
	}

	/*
	* Class:     trab1_Hardware
	* Method:    create_di
	* Signature: (I)V
	*/
	JNIEXPORT void JNICALL Java_trab1_Hardware_create_1di
		(JNIEnv *, jobject, jint port){
		printf("Vai fazer o codigo para comunicar!!\n");
		printf("Put here the code for creating digital input %d", port);
		create_DI_channel(port);
	}

	/*
	* Class:     trab1_Hardware
	* Method:    create_do
	* Signature: (I)V
	*/
	JNIEXPORT void JNICALL Java_trab1_Hardware_create_1do
		(JNIEnv *, jobject, jint port){
		create_DO_channel(port);
	}

	/*
	* Class:     trab1_Hardware
	* Method:    read_port
	* Signature: (I)I
	*/
	JNIEXPORT jint JNICALL Java_trab1_Hardware_read_1port
		(JNIEnv *, jobject, jint port){
		return 1;
	}

	/*
	* Class:     trab1_Hardware
	* Method:    move_x_left
	* Signature: ()V
	*/
	JNIEXPORT void JNICALL Java_trab1_Hardware_move_1x_1left
		(JNIEnv *, jobject){
		
	}

	/*
	* Class:     trab1_Hardware
	* Method:    move_x_right
	* Signature: ()V
	*/
	JNIEXPORT void JNICALL Java_trab1_Hardware_move_1x_1right
		(JNIEnv *, jobject);

	/*
	* Class:     trab1_Hardware
	* Method:    move_y_in
	* Signature: ()V
	*/
	JNIEXPORT void JNICALL Java_trab1_Hardware_move_1y_1in
		(JNIEnv *, jobject);

	/*
	* Class:     trab1_Hardware
	* Method:    move_y_out
	* Signature: ()V
	*/
	JNIEXPORT void JNICALL Java_trab1_Hardware_move_1y_1out
		(JNIEnv *, jobject);

	/*
	* Class:     trab1_Hardware
	* Method:    move_z_up
	* Signature: ()V
	*/
	JNIEXPORT void JNICALL Java_trab1_Hardware_move_1z_1up
		(JNIEnv *, jobject);

	/*
	* Class:     trab1_Hardware
	* Method:    move_z_down
	* Signature: ()V
	*/
	JNIEXPORT void JNICALL Java_trab1_Hardware_move_1z_1down
		(JNIEnv *, jobject){
		WriteDigitalU8(4, 0x20);
	}

	/*
	* Class:     trab1_Hardware
	* Method:    stop_x
	* Signature: ()V
	*/
	JNIEXPORT void JNICALL Java_trab1_Hardware_stop_1x
		(JNIEnv *, jobject);

	/*
	* Class:     trab1_Hardware
	* Method:    stop_y
	* Signature: ()V
	*/
	JNIEXPORT void JNICALL Java_trab1_Hardware_stop_1y
		(JNIEnv *, jobject);

	/*
	* Class:     trab1_Hardware
	* Method:    stop_z
	* Signature: ()V
	*/
	JNIEXPORT void JNICALL Java_trab1_Hardware_stop_1z
		(JNIEnv *, jobject);

	/*
	* Class:     trab1_Hardware
	* Method:    stop_emergency
	* Signature: ()V
	*/
	JNIEXPORT void JNICALL Java_trab1_Hardware_stop_1emergency
		(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
